AWSTemplateFormatVersion: "2010-09-09"
Description: A template to create an S3 bucket and cloudfront distribution for a static website
Parameters:
  BucketName:
    Description: The name of the new bucket
    Type: String
    MinLength: "3"
    MaxLength: "63"
    AllowedPattern: "[a-z0-9-]*"

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - MyS3Bucket
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Origins:
          - DomainName: !Sub "${MyS3Bucket}.s3.amazonaws.com"
            Id: S3Origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
              OriginReadTimeout: 30
        DefaultCacheBehavior:
          AllowedMethods:
            - "GET"
            - "HEAD"
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
      - CloudFrontDistribution
      - MyS3Bucket
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"
